default_velocity_scaling_factor: 0.1
default_acceleration_scaling_factor: 0.1

joint_limits: 
  limb1_to_base_link:
    has_velocity_limits: true
    max_velocity: 10.0
    has_acceleration_limits: false
    max_acceleration: 5.0
  
  limb2_to_limb1:
    has_velocity_limits: true
    max_velocity: 10.0
    has_acceleration_limits: false
    max_acceleration: 5.0
  
  limb3_to_limb2:
    has_velocity_limits: true
    max_velocity: 10.0
    has_acceleration_limits: false
    max_acceleration: 5.0
  
  limb4_to_limb3:
    has_velocity_limits: true
    max_velocity: 10.0
    has_acceleration_limits: false
    max_acceleration: 5.0
  
  limb5_to_limb4:
    has_velocity_limits: true
    max_velocity: 10.0
    has_acceleration_limits: false
    max_acceleration: 5.0
  
  limb6_to_limb5:
    has_velocity_limits: true
    max_velocity: 10.0
    has_acceleration_limits: false
    max_acceleration: 5.0